### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by exnerd** [mgsg/domoticz-sonos-plugin#2]
Hi, 

with the new version of domoticz (v2.2284) I thought to give the Sonois plugin another chance. But the installation instructions are not completly clear to me.
   - Activate the Sonos hardware in the Setup->Hardware section
I didn't find any Sonos hardware in the Hardware section, do I need to copy plugin, choose the Beta program ? Or anything else for that matter.

Regards,
Benoit

**Comment by mgsg** [comment]
Sorry, as it is now, the last version uploaded is merged with Domoticz 2180. 

You can test the code in two different / alternative ways:
1. Just copy the executable for raspberry pi (/raspi) and the web resources (/www) over your current domoticz installation (but do a backup of those files!).
2. Copy the source files over a fresh domoticz v2.180 source installation and compile.

I did not have a lot of time the last weeks, so I couldn't remerge with a more recent version. I hope to have more time (again) in the coming weeks to remerge again and correct bugs.
