### ISSUE TITLE
What has this done to Domoticz?

### ISSUE THREAD

**Issue by leecollings** [mgsg/domoticz-sonos-plugin#3]
I copied the files from the /raspi/ folder into the root, and from the /www/ into the /www/ folder, but now when I run Domoticz all I see is an input field int he top left corner, which is blank.

It looks like it's completely overwritten Domoticz!

![screen shot 2017-05-16 at 10 22 34](https://cloud.githubusercontent.com/assets/6681733/26099092/9b130bca-3a21-11e7-8cdb-4a877e117a16.png)

What's happened here, and is this plugin actually working?

**Comment by mgsg** [comment]
This plugin is not working anymore. I uploaded it to github just in case somebody wanted to continue working on it. Sorry.
